### LOGIn
POST http://localhost:2003/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "hilmau@mail",
    "email": "hilmau@mail",
    "password": "mantabgan"
}

### KEEP LOGGED IN
GET http://localhost:2003/auth/keeploggedin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJoaWxtb28iLCJyb2xlIjoidXNlciIsImlhdCI6MTYzODg2Nzg0MywiZXhwIjoxNjM4OTExMDQzfQ.jIrxZhBtIpXDRwp5C1iz-p3WitlQSmC4DduApHNZP_k

### CHANGE PASS
PATCH http://localhost:2003/auth/changeprofilepass/4 HTTP/1.1
Content-Type: application/json

{
    "currentPass": "haihai",
    "newPass": "mantab",
    "confirmNewPass": "mantab"
}