### GET PRODUCTS
GET http://localhost:2003/product/getproducts HTTP/1.1
Content-Type: application/json

###
GET http://localhost:2003/product/getcategories HTTP/1.1
Content-Type: application/json

###
GET http://localhost:2003/transaction/historydetails/18 HTTP/1.1
Content-Type: application/json